### ISSUE TITLE
Error when running MemProcFS-Analyzer.ps1

### ISSUE THREAD

**Issue by lincion** [evild3ad/MemProcFS-Analyzer#48]
![MA12`RWSH_WSK2LA%FO YHN](https://github.com/user-attachments/assets/28443291-80ab-457a-aef2-36b5c6b6363f)

**Comment by evild3ad** [comment]
Get-MpComputerStatus is a cmdlet that checks for the status of your antimalware software...Microsoft Defender AntiVirus by default. What kind of Windows are you using?

**Comment by lincion** [comment]
> Get-MpComputerStatus is a cmdlet that checks for the status of your antimalware software...Microsoft Defender AntiVirus by default. What kind of Windows are you using?

Microsoft Windows [ver 10.0.19045.5011]

**Comment by evild3ad** [comment]
Are you using third-party antivirus? I recommend disabling of your antivirus when processing data with forensic tools (including MemProcFS). If you are using 3rd-party antivirus you can disable the 'MicrosoftDefender' function in the main at the end of the script.

**Comment by lincion** [comment]
> Are you using third-party antivirus? I recommend disabling of your antivirus when processing data with forensic tools (including MemProcFS). If you are using 3rd-party antivirus you can disable the 'MicrosoftDefender' function in the main at the end of the script.

I shutdown the third-party antivirus and make 'MicrosoftDefender' disabled,
![image](https://github.com/user-attachments/assets/db3cfc44-e576-4fbc-bbee-13236102d908)
but it doesn't work
![image](https://github.com/user-attachments/assets/c6a5aed7-3e95-478a-b432-e74c2a5012b7)

And this is the MemProcFS shows:
![image](https://github.com/user-attachments/assets/af64ea9f-bec8-465d-8a28-292d544fb4a6)

**Comment by evild3ad** [comment]
You have already created an [issue](https://github.com/ufrisk/MemProcFS/issues/330) for this and received a clear answer from @ufrisk. You can also re-create the memory dump or use any memory sample for your testing purposes.

Sorry, but i seems that you don't understand anything what I write or what you are doing.

When you are using third-party antivirus you don't need this 'MicrosoftDefender' function. You can manually disable your third-party antivirus all the time. This function disables the realtime protection temporarily when you would use Microsoft Defender AntiVirus. To use this function you have to disable the tamper protection manually (one-time).

Because of the presence of a third-party antivirus the built-in antivirus got auto-disabled. An uninstallation would be needed and a restart of your machine. Don't run MemProcFS-Analyzer for testing, simply run the cmdlet `Get-MpComputerStatus`.

I highly recommend you to start with he basics in memory acquisition and memory analysis first...do some manual analysis before you switch to an advanced automation. Good luck!
